### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by manishyadavv** [nicolasblanco/wizard_app#1]
When email is typed in it ,it accepts wrongly written email like
1. Example@ 
2.Example@gmailcom
3.Example@xyz

**Comment by nicolasblanco** [comment]
This app is an example. It does not implement a "real" validation of emails. Search 'email regex ruby' and validate the email with a more restricted regexp...

**Comment by joshm1204** [comment]
NameError (uninitialized constant Wizard)
